name: Crowdin Action

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - next

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ZapSquared'

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.8
      with:
        upload_translations: true
        download_translations: true
        skip_untranslated_strings: true
        commit_message: 'chore(locales): new Crowdin translations'
        localization_branch_name: 'l10n_next'
        crowdin_branch_name: 'next'
        create_pull_request: true
        pull_request_title: 'chore(locales): new Crowdin translations'
        pull_request_body: 'New Crowdin translations'
        pull_request_labels: 'affects:locale, priority:p2'
        pull_request_base_branch_name: next
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
